#ifndef _CONSTANTS_H_
#define _CONSTANTS_H_

// Frame search constants
#define FRAME_SEARCH_GRID_SIZE 1024
#define FRAME_SEARCH_THREADS_PER_BLOCK 1024
#define FRAME_SEARCH_NUM_K_BITS 4
#define FRAME_SEARCH_NUM_P_BITS 16
#define FRAME_SEARCH_MAX_CANDIDATES (1 << 30)
#define FRAME_SEARCH_MAX_FRAMES (1 << 24)
#define FRAME_SEARCH_KERNEL_PATTERN_INCREMENT 0x1000000ULL
#define FRAME_SEARCH_TOTAL_MINIMAL_FRAMES 2102800


// Common buffer sizes
#define BINARY_STRING_BUFFER_SIZE 65
#define MESSAGE_BUFFER_SIZE 64

#endif